import { useEffect, useRef, useState } from 'react'
import { api } from '../lib/api'
import { DEMO } from '../lib/supabase'
import { demoInsights } from '../lib/demoData'

export default function InsightsPanel({ hotelId }) {
  const [days, setDays] = useState(7)
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const request = useRef(0)
  useEffect(() => {
    request.current++
    setResult(null)
    setError('')
    setLoading(false)
    return () => { request.current++ }
  }, [hotelId, days])
  async function generate() {
    const id = ++request.current
    setLoading(true)
    setError('')
    setResult(null)
    try {
      const response = DEMO ? await demoInsights(hotelId, days) : await api('/insights', { method: 'POST', body: { hotelId, days } })
      if (id === request.current) setResult(response)
    } catch (err) { if (id === request.current) setError(err.message) }
    finally { if (id === request.current) setLoading(false) }
  }
  const metrics = result?.metrics
  function money(value) {
    try { return new Intl.NumberFormat('en-PH', { style: 'currency', currency: metrics?.currency || 'PHP', maximumFractionDigits: 2 }).format(value) }
    catch { return `${Number(value).toFixed(2)} ${metrics?.currency || ''}` }
  }
  return <section className="dashboard-panel insights-panel" aria-label="Hotel performance insights">
    <div className="panel-heading"><div><h2><i className="bi bi-stars me-2 text-brand" />A clearer view of your hotel</h2><p>{DEMO ? 'Explore sample insights using your demo workspace.' : 'Turn your operational numbers into practical next steps.'}</p></div>
      <div className="insights-controls"><select className="form-select form-select-sm" aria-label="AI reporting period" value={days} onChange={event => setDays(Number(event.target.value))} disabled={loading}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option></select><button className="btn btn-primary btn-sm" disabled={loading || !hotelId} onClick={generate}>{loading ? 'Generating…' : DEMO ? 'Show sample insights' : 'Generate AI insights'}</button></div>
    </div>
    {error && <div className="alert alert-warning" role="alert">{error}</div>}
    {loading && <p role="status" className="insights-summary">Reviewing your hotel's metrics. This can take up to 20 seconds…</p>}
    {!result && !loading && <p className="insights-summary mb-0">See what your occupancy, restaurant activity, and billing figures are telling you. Request a summary when you need it.</p>}
    {result && <div aria-live="polite">
      <p className="insights-note">{result.demo ? 'Sample insights · Rule-based demo, not generated by AI' : `AI-generated · ${result.cached ? 'Cached summary' : 'New summary'}`} · {new Date(result.generatedAt).toLocaleString()}</p>
      <p className="insights-summary">{result.insight.summary}</p>
      <dl className="insights-metrics">
        {[
          ['Occupancy now', `${metrics.rooms_total ? Math.round(metrics.rooms_occupied / metrics.rooms_total * 100) : 0}%`],
          ['Reservations created', metrics.reservations_created],
          ['Restaurant order value', money(metrics.restaurant_sales)],
          ['Invoiced in period', money(metrics.invoiced)],
          ['Collected in period', money(metrics.collected)],
          ['Outstanding now', money(metrics.outstanding)],
        ].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}
      </dl>
      <div className="row g-3"><div className="col-md-6 insights-section"><h3>What stands out</h3><ul>{result.insight.observations.map((text, i) => <li key={i}>{text}</li>)}</ul></div><div className="col-md-6 insights-section"><h3>Your next steps</h3><ol>{result.insight.actions.map((text, i) => <li key={i}>{text}</li>)}</ol></div></div>
      <p className="insights-note mb-0">Period: {metrics.period_start} to {metrics.period_end} (UTC). Occupancy and outstanding balances are snapshots at generation. Restaurant values exclude cancelled orders; collections may cover older invoices. Review suggestions against your records.</p>
    </div>}
    {!DEMO && <p className="insights-note mt-3 mb-0">On-demand AI · Up to 5 new requests per person and 30 across the classroom daily, subject to the provider's free quota. Cached results do not consume another model request.</p>}
  </section>
}
